### ISSUE TITLE
[FEATURE] PlotSquared support

### ISSUE THREAD

**Issue by romsto** [RomainStorai/HoloBroadcast#3]
**Describe the solution you'd like**
Add support to PlotSquared so that when the player enters a plot, they can see an HUD.

**Additional context**
Should only support the last version of it.

**Comment by RomainStorai** [comment]
PlotSquared is 1.18+ based so it requires Java 17. Since HoloBroadcast is Java 8, it's impossible to use Plot² unless using reflections.
This issue is now paused until HB go through Java 17 or Plot² is really required.
